global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'allin-platform'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # AllIN Backend Application
  - job_name: 'allin-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AllIN Frontend Application
  - job_name: 'allin-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Nginx metrics (if nginx-prometheus-exporter is configured)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Business metrics from the application
  - job_name: 'allin-business-metrics'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics/business'
    scrape_interval: 30s

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:5000'
        - 'frontend:3000'
    metrics_path: '/health'
    scrape_interval: 30s
    
  # Custom application metrics
  - job_name: 'allin-custom-metrics'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics/custom'
    scrape_interval: 20s
    
remote_write:
  # Optional: Send metrics to external monitoring service
  # - url: "https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push"
  #   basic_auth:
  #     username: "your_username"
  #     password: "your_password"