global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'allin-platform'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'allin-platform'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Backend API metrics (assuming /metrics endpoint)
  - job_name: 'backend-api-prod'
    static_configs:
      - targets: ['backend-prod:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Backend API metrics (development)
  - job_name: 'backend-api-dev'
    static_configs:
      - targets: ['backend-dev:7000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis metrics (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Nginx metrics (requires nginx-prometheus-exporter)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
